module.exports.constants = {

 
    user: {
        //Registration and Login
        "USERNAME_REQUIRED": "Email is required",
        "FIRSTNAME_REQUIRED": "Firstname is required",
        "LASTNAME_REQUIRED": "Lastname is required",
        "PHONE_REQUIRED": "Phone number is required",
        "EMAIL_REQUIRED": "Email is required",
        "ROLE_REQUIRED": "Role is required",
        "EMAIL_EXIST": "Email-Id already exists.",
        "NUMBER_EXIST": "Mobile number is already exists.",
        "WRONG_EMAIL": "Email-Id does not exists",
        "PASSWORD_REQUIRED": "Password is required",
        "PAYLOAD_REQUIRED": "Payload is required",
        "UNVERIFIED": "You have not verified your account. Please verify",
        "USERNAME_NOT_APPROVED": "You have not approved by the admin",
        "SUCCESSFULLY_REGISTERED": "Successfully registered",
        "SUCCESSFULLY_LOGGEDIN": "Successfully logged in",
        "WRONG_USERNAME": "Username does not exists",
        "WRONG_PASSWORD": "Password is wrong!",
        "CURRENT_PASSWORD": "Current Password is wrong!",
        "INVALID_USER": "Invalid User. Your email does not exist to our system.",
        "ALREADY_VERIFIED": "You have already verified your email. Please login to website.",
        "ERROR_MAIL": "There is some error to send mail to your email id.",
        "LINK_MAIL": "Link for reset password has been sent to your email id.",
        "PASSWORD_CHANGED": "Password has been changed",
        "USERNAME_ALREADY": "Username is already exits.",
        "USERNAME_INACTIVE": "User is inactive",
        "CONPASSWORD_REQUIRED": "Confirm Password is required",
        "CURRENTPASSWORD_REQUIRED": "Current Password is required",
        "CONFIRM_PASSWORD_NOTMATCH": "Confirm Password is not Match",
        "ID_REQUIRED": "id Is Required",
        "UPDATED_USER": "User updated successfully.",
        "USERNAME_VERIFIED": "User is not verified.",
        "INVALID_CRED" : "Invalid login credentials.",
        "COMPANY_REQUIRED": " Company id required.",
        "DOMAIN_REQUIRED": "Domain key required.",
        "CONTACT_ADMIN":"Unable to login. Please contact admin.",
        "INVALID_IP" : "Ip address is not in whitelist.",
        "INVALID_LOCATION":"Unable to login .Please login at company\'s location.",
        "INVALID_IMAGE":"Invalid video type.",
        "VERIFICATION_SENT" : "Verfication OTP has sent to your email Please crosscheck your email.",
        "NOT_EXIST":"User not exist.",
        "DELETED" : "User deleted successfully.",
        "SUCCESSFULLY_SENT":"Email sent successfully."
    },
    CATEGORY: {
        NAME_REQUIRED: 'Name is required',
        ID_REQUIRED: 'Id is required',
        NAME_EXIST: 'Category with same name already exists',
        UPDATED: 'Category updated successfully',
        ADDED: 'Category added successfully',
        INVALID_ID: 'Invalid id',
        ALREADY_IN_USE: 'Category is already in use',
        DELETED: 'Category deleted successfully',
      },
      campaign: {
        NAME_REQUIRED: 'Name is required',
        ID_REQUIRED: 'Id is required',
        NAME_EXIST: 'Campaign with same name already exists',
        UPDATED: 'Campaign updated successfully',
        ADDED: 'Campaign added successfully',
        INVALID_ID: 'Invalid id',
        ALREADY_IN_USE: 'Campaign is already in use',
        DELETED: 'Campaign deleted successfully',
      },
      group: {
        NAME_REQUIRED: 'Name is required',
        ID_REQUIRED: 'Id is required',
        NAME_EXIST: 'Group with same name already exists',
        UPDATED: 'Group updated successfully',
        ADDED: 'Group added successfully',
        INVALID_ID: 'Invalid id',
        ALREADY_IN_USE: 'Group is already in use',
        DELETED: 'Group deleted successfully',
      },
}
